# 워크플로우 이름
name: Deploy to Workers R2

# 트리거 설정: main 브랜치에 푸시될 때 실행
on:
  push:
    branches: [master]

jobs:
  # 배포 작업 정의
  deploy:
    # GitHub Actions 실행 환경
    runs-on: ubuntu-latest
    
    # 작업 단계 정의
    steps:
      # 1. 저장소 코드 체크아웃
      - uses: actions/checkout@v3
      
      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # 3. 프로젝트 의존성 설치
      - name: Install dependencies
        run: npm install
        
      # 4. 프로젝트 빌드
      - name: Build
        run: npm run build

      # 5. AWS CLI 설정
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto
          aws configure set default.s3.endpoint_url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          aws configure set default.s3.signature_version s3v4
          # 재시도 횟수 증가
          aws configure set default.s3.max_attempts 10
          # 타임아웃 설정
          aws configure set default.s3.timeout 60

      # 6. Check Bucket Settings
      - name: Check Bucket Settings
        run: |
          echo "Checking bucket ACL..."
          aws --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com s3api get-bucket-acl --bucket h9-vue-recipes-assets || true
          
          echo "Checking bucket policy..."
          aws --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com s3api get-bucket-policy --bucket h9-vue-recipes-assets || true

      # 7. R2에 파일 업로드
      - name: Upload to R2
        run: |
          # dist 디렉토리 내용 확인
          echo "Contents of dist directory:"
          ls -la dist/

          # 각 파일을 개별적으로 업로드
          for file in dist/*; do
            filename=$(basename "$file")
            echo "Uploading $filename..."
            echo "File size: $(ls -lh "$file" | awk '{print $5}')"
            
            # 최대 3번까지 재시도
            for i in {1..3}; do
              if aws --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com s3 cp "$file" "s3://h9-vue-recipes-assets/$filename" --debug; then
                echo "Successfully uploaded $filename"
                break
              else
                echo "Attempt $i failed for $filename, retrying..."
                if [ $i -eq 3 ]; then
                  echo "Failed to upload $filename after 3 attempts"
                  exit 1
                fi
                sleep 5
              fi
            done
          done

      # 8. 업로드된 파일 URL 출력
      - name: Print File URLs
        run: |
          echo "Uploaded files are available at:"
          echo "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/h9-vue-recipes-assets/h9-vue-recipes.es.js"
          echo "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/h9-vue-recipes-assets/h9-vue-recipes.css"
          echo "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/h9-vue-recipes-assets/h9-vue-recipes.umd.js" 