# 워크플로우 이름
name: Deploy to Workers R2

# 트리거 설정: main 브랜치에 푸시될 때 실행
on:
  push:
    branches: [master]

jobs:
  # 배포 작업 정의
  deploy:
    # GitHub Actions 실행 환경
    runs-on: ubuntu-latest
    
    # 작업 단계 정의
    steps:
      # 1. 저장소 코드 체크아웃
      - uses: actions/checkout@v3
      
      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # 3. 프로젝트 의존성 설치
      - name: Install dependencies
        run: npm install
        
      # 4. 프로젝트 빌드
      - name: Build
        run: npm run build

      # 5. AWS CLI 설정 (R2는 S3 호환 API를 사용)
      - name: Configure AWS CLI
        run: |
          # R2 액세스 키 설정
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          # R2는 region이 필요 없음
          aws configure set default.region auto
          # R2 엔드포인트 설정
          aws configure set default.s3.endpoint_url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          # S3 v4 서명 사용
          aws configure set default.s3.signature_version s3v4
          # 업로드 재시도 횟수 증가
          aws configure set default.s3.max_attempts 10
          # 타임아웃 설정
          aws configure set default.s3.timeout 60

      # 6. R2에 파일 업로드
      - name: Upload to R2
        run: |
          # dist 폴더의 내용을 R2 버킷에 동기화
          # --delete: 버킷에 있지만 로컬에 없는 파일 삭제
          # --no-progress: 진행 상황 표시 비활성화
          aws --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com s3 sync dist/ s3://h9-vue-recipes-assets/ --delete --no-progress 